version: '3.7'

#consul集群配置
services:
  consul_node_1:
    &consul
    container_name: consul_node_1
    image: ${CONSUL_IMAGE}
    hostname: consul_node_1
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.11
    command: ["agent", "-data-dir", "/consul/data", "-config-dir", "/consul/config", "-ui"]
#    extra_hosts:
#      - consul_node_1:${IP_ADDR_PREFIX}.11
#      - consul_node_2:${IP_ADDR_PREFIX}.12
#      - consul_node_3:${IP_ADDR_PREFIX}.13
    volumes:
      - ${DOCKER_VOLUME}/consul/node1:/consul/data
      - ${DOCKER_CONFIG}/consul/config.json:/consul/config/config.json
      - ${DOCKER_CONFIG}/consul/node1.json:/consul/config/node1.json
  consul_node_2:
    <<: *consul
    container_name: consul_node_2
    hostname: consul_node_2
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.12
    volumes:
      - ${DOCKER_VOLUME}/consul/node2:/consul/data
      - ${DOCKER_CONFIG}/consul/config.json:/consul/config/config.json
      - ${DOCKER_CONFIG}/consul/node2.json:/consul/config/node2.json
  consul_node_3:
    <<: *consul
    container_name: consul_node_3
    hostname: consul_node_3
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.13
    volumes:
      - ${DOCKER_VOLUME}/consul/node3:/consul/data
      - ${DOCKER_CONFIG}/consul/config.json:/consul/config/config.json
      - ${DOCKER_CONFIG}/consul/node3.json:/consul/config/node3.json
