version: '3.8'

networks:
  cluster-network:
    external: true

services:
  vault:
    container_name: vault
    image: ${VAULT_IMAGE}
    hostname: vault
    ports:
    - 8200:8200
    networks:
      cluster-network:
        ipv4_address: ${IP_ADDR_PREFIX}.91
